# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import orchestrator_pb2 as orchestrator__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orchestrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessCommand = channel.unary_unary(
                '/jarvis.Orchestrator/ProcessCommand',
                request_serializer=orchestrator__pb2.CommandRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.StreamCommand = channel.unary_stream(
                '/jarvis.Orchestrator/StreamCommand',
                request_serializer=orchestrator__pb2.CommandRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.CommandResponse.FromString,
                _registered_method=True)


class OrchestratorServicer:
    """Missing associated documentation comment in .proto file."""

    def ProcessCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessCommand,
                    request_deserializer=orchestrator__pb2.CommandRequest.FromString,
                    response_serializer=orchestrator__pb2.CommandResponse.SerializeToString,
            ),
            'StreamCommand': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCommand,
                    request_deserializer=orchestrator__pb2.CommandRequest.FromString,
                    response_serializer=orchestrator__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jarvis.Orchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jarvis.Orchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Orchestrator:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jarvis.Orchestrator/ProcessCommand',
            orchestrator__pb2.CommandRequest.SerializeToString,
            orchestrator__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jarvis.Orchestrator/StreamCommand',
            orchestrator__pb2.CommandRequest.SerializeToString,
            orchestrator__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
